### ISSUE TITLE
管理组织页面，用户列表展示异常

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#10]
## 环境
- 测试服务

## 问题描述

![image](https://user-images.githubusercontent.com/30621793/218649727-7a077c32-f33b-429b-b4d0-ac167f7fc2a4.png)

### 期望

用户列表中能正常展示当前组织中包含的用户:
- organization.spec.admin
- organization.spec.clients
 
### 实际

```
HttpException
```

**Comment by Jandiasnow** [comment]
@dayuy 看下，前端应该不需要改动

**Comment by dayuy** [comment]
已修，iam-provider的问题
