### ISSUE TITLE
通道详情-合约列表中的合约名称应该展示 `chaincode.spec.id`

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#101]
![image](https://user-images.githubusercontent.com/30621793/225610686-f83da33c-5a05-4223-ab40-697569795729.png)

**Comment by dayuy** [comment]
取chaincode.displayName @Jandiasnow 
`
query getChannel(){
  channel{
    chaincode {
      displayName 
    }
  }
}
`
