### ISSUE TITLE
提议管理：部署合约后需要刷新才能在提议管理里看到部署提议

### ISSUE THREAD

**Issue by Lanture1064** [bestchains/bc-console#107]
![6D28290E-F8EB-4017-8D96-120142E136AA](https://user-images.githubusercontent.com/34346740/225844012-684fc32c-db48-496f-883e-74b700744296.png)
合约管理中点击部署合约，显示【已提交】，但需要手动刷新才能显示上面的部署提议，可能需要重新载入
（另：能否增加提议类型？）

**Comment by dayuy** [comment]
DeployChaincodeProposal: 创建合约
UpgradeChaincodeProposal: 更新合约
@Jandiasnow  提议类型
