### ISSUE TITLE
网络管理-新建网络时共识集群最大值未设限制

### ISSUE THREAD

**Issue by marsdawe** [bestchains/bc-console#109]
新建网络时共识集群最大值未设限制，最大值是5，超过5时红字提示。
![9fae4523a8e8b4bde688f5e476be8f92](https://user-images.githubusercontent.com/44803190/226265428-c4f7c678-7a6d-475b-9046-4dba1d2c25d1.png)

**Comment by Jandiasnow** [comment]
超过 5 时会自动填充为 5，已修改
