### ISSUE TITLE
策略管理中应展示策略内容

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#111]

**Comment by marsdawe** [comment]
https://lanhuapp.com/web/#/item/project/stage?tid=e1b23e90-0c07-4d9d-b87a-7f5f636c41bf&pid=ed4a8712-6b7c-4875-91fa-8a86b04b6aa9&versionId=1303d2d1-f821-41fc-9489-06a2d6f21c4c&docId=c11fd707-1bb5-4797-bb7e-455fc7fa3ef3&docType=axure&pageId=8a25c1185dbd4a388f4a23a5322713fd&image_id=c11fd707-1bb5-4797-bb7e-455fc7fa3ef3&parentId=342ece71-8214-426d-9da9-8648c822001c
设计图完成
