### ISSUE TITLE
网络详情-合约数量展示不正确

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#112]
![481f378f7f1ff1149911718744c7de62](https://user-images.githubusercontent.com/30621793/227441913-b6e9844f-dec1-4846-9022-7ca3ec4c9827.png)

**Comment by Jandiasnow** [comment]
需要提供相关字段 @dayuy

**Comment by dayuy** [comment]
chaincode{name, createByMe} @Jandiasnow
