### ISSUE TITLE
调整主题等内容以完全符合产品设计

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#115]

**Comment by dayuy** [comment]
主题颜色定制，设计稿是橘色

**Comment by zggmd** [comment]
主题色定制

目前 只需要 primaryColor: string 字段即可

**Comment by dayuy** [comment]
全局配置API: query getGlobalConfig()
@zggmd

**Comment by dayuy** [comment]
1. 主题颜色 done
2. 产品icon  done
@bjwswang  可以帮关闭此issue
