### ISSUE TITLE
联盟详情页面-联盟成员

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#12]
联盟处在`FederationPending`和`FederationDissolved`时，不允许删除成员

![image](https://user-images.githubusercontent.com/30621793/218654345-b55de091-fc05-462c-a0ec-6efb22eda80f.png)

### 期望
- 联盟还未激活，`删除`按钮应该是灰色，不可点击

### 实际
- 可点击，发起删除成员的提议

**Comment by Jandiasnow** [comment]
已修改

**Comment by bjwswang** [comment]
@Jandiasnow PR提交的时候通过" Fix: #12 " 可直接关闭issue 
参考 `https://github.com/bestchains/fabric-operator/pull/99`
