### ISSUE TITLE
合约升级报错

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#130]
![image](https://user-images.githubusercontent.com/30621793/229073113-2d6aba3e-9318-4248-b6b5-d901d6b82dfa.png)
![image](https://user-images.githubusercontent.com/30621793/229073130-96360479-fc3c-4ab9-a1e8-c8ea16e1b15d.png)

**Comment by Jandiasnow** [comment]
@dayuy 非前端问题，看下原因

**Comment by bjwswang** [comment]
closed as this issue fixed by https://github.com/bestchains/fabric-operator/commit/3312395eb4a2b3b7ec9b2b14310aac6ba1800fd3
