### ISSUE TITLE
网络停止报错

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#134]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/30621793/229400268-a2283b35-5b70-4242-89c3-514a9163e8ce.png">

## 期望
点击停止后，应该发起一个解散网络的proposal

**Comment by bjwswang** [comment]
@marsdawe 确认下产品逻辑

**Comment by marsdawe** [comment]
网络停止：
a、如网络里面，没有任何通道，或通道只有创建组织，可以直接停止网络
 b、如网络通道里面有其他组织，停止网络需要发起提议投票。

**Comment by dayuy** [comment]
「停止网络」
1. 如果网络有通道，目前会提示
![image](https://user-images.githubusercontent.com/17400942/230537321-62d16a6c-824d-4797-a244-6208ad96912b.png)
2. 如果没有通道，则会发起proposal：DissolveNetworkProposal。
「删除网络」
1. 同上
2. 如果没有通道，则会删除 network
-------------
目前是这样处理的。可能需要提示优化下，看1需要怎么提示？@marsdawe

**Comment by marsdawe** [comment]
「网络停止」
1、网络有通道，
a、如通道里有其他组织，则发起停止提议
b、如通道里没有其他组织，直接停止。
2、网络没有通道，直接停止。

「网络删除」
3、网络停止后，网络创建者，可以删除网络，

**Comment by dayuy** [comment]
「直接停止」
没有这个动作，停止就是发起一个Dissolve的提议

**Comment by marsdawe** [comment]
「网络停止」
点击**停止**，弹窗发起网络停止提议

a、如通道里有其他组织，点击**确定**，继续弹窗发送提议成功。
<img width="437" alt="image" src="https://user-images.githubusercontent.com/44803190/231926563-49a6f831-ca74-435d-b075-14461ef63075.png">

b、如通道里没有其他组织，点击**确定**，直接提示“提议成功”，

**Comment by bjwswang** [comment]
verified
