### ISSUE TITLE
通道创建时，弹窗提示内容不正确

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#135]
## 期望
提示成功或者失败

## 实际
提示到提议管理中查看

**Comment by bjwswang** [comment]
@marsdawe 确认下产品逻辑，创建通道应该是不需要提议管理

**Comment by marsdawe** [comment]
创建通道：
a、创建者不选择配置成员创建通道，直接创建通道，不需要发起邀请提议。
b、创建者选择配置成员，需要发起邀请，需要配置的成员同意才可创建通道。

**Comment by dayuy** [comment]
目前的逻辑是，不管有没有选择配置成员，都是直接创建通道了 @marsdawe

**Comment by marsdawe** [comment]
时间问题，下个版本再完善。当前版本就直接创建通道吧，这个闭环还需要**去掉创建时的发起提议弹窗**
