### ISSUE TITLE
上传合约代码的提示信息应该为中文

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#136]
## 实际

<img width="542" alt="image" src="https://user-images.githubusercontent.com/30621793/229401452-c48fb2e9-a809-4831-bdfd-abcebd79b779.png">

**Comment by Jandiasnow** [comment]
![image](https://user-images.githubusercontent.com/19659148/230334631-a2049b46-80ee-4f83-9f11-c78088a8d04c.png)
未复现，复现后再处理
