### ISSUE TITLE
新建合约时，没有针对网络内部的合约名称版本号做去重校验

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#137]
## 期望
网络中相同名称的合约版本号不能有重复

## 实际
允许
网络名称:  saas

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/30621793/229402913-5a0c697e-10ce-45ae-b0b8-c1156297df67.png">

**Comment by dayuy** [comment]
在「创建合约」、「升级合约」提交时校验重复数据，通过 getChaincodebuilds($network: String!, $version: String, $displayName: String)， 如果返回数组中大于0，则重复。
@Jandiasnow

**Comment by bjwswang** [comment]
后端有去重，前端也应该有对应提示
