### ISSUE TITLE
通道切换后，区块链浏览器总览页数据展示不正确

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#140]
## 期望

切换通道后，总览页数据马上更新

## 实际

没有及时更新，如下图所示:

切换到通道`saas_nftdev`后，其只有一个区块，而总览页展示的数据不正确

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/30621793/229406022-fb5d8d72-dc2c-49f4-8360-538e143cdafb.png">

**Comment by Jandiasnow** [comment]
未复现，复现后处理，应该是数据还在加载中
