### ISSUE TITLE
联盟驱逐成员，提议成功后，成员仍然存在

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#146]

**Comment by Jandiasnow** [comment]
@dayuy 看下原因

**Comment by dayuy** [comment]
1. DeleteMemberProposal voted, fed spec.memeber没有变更 @bjwswang

**Comment by bjwswang** [comment]
@Abirdcfly  https://github.com/bestchains/fabric-operator/issues/226 
后端处理成员删除的原因，没有给被删除者投票权

**Comment by bjwswang** [comment]
> 1. DeleteMemberProposal voted, fed spec.memeber没有变更 @bjwswang

前端需要验证确认，被删除member在该组织内部不作为任何网络的initiator

**Comment by bjwswang** [comment]
closed as verified
