### ISSUE TITLE
【产品】优化合约代码文件夹上传

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#151]
## 提议
通过检测`.bcignore`文件，实现有针对性的忽略上传文件。

`.bcignore`文件内容
```
.git
.github
test
```

## 原因

目前，对文件夹上传需要限制文件数量<100,导致本地合约测试经常需要频繁清理 `.git` `.github`等，因此需要允许用户自定义`.bcignore`，用于忽略不需要的文件

**Comment by Jandiasnow** [comment]
前端已修改，浏览器还是会加载所有文件（前端只能控制只加载哪些后缀结尾的文件），只是只展示并上传过滤之后的，并不能解决选文件时卡顿的问题
