### ISSUE TITLE
升级合约操作变成新建合约，且合约名称有误

### ISSUE THREAD

**Issue by Lanture1064** [bestchains/bc-console#153]
![image](https://user-images.githubusercontent.com/34346740/230812268-784fafa5-af0e-42be-9363-d0ff7153ecfd.png)

如图，升级合约 timelock4 至 v0.1.2 版本的操作变成了新建一个名为“chaincodebuild-ist9e"，版本号为 v0.1.2 的合约，且点进该合约详情显示的合约名称与列表页不符；两个合约名字均无法被 client 调用，调用 timelock4 合约显示为未升级状态

**Comment by Jandiasnow** [comment]
1. 详情页合约名： name 改为 displayName: 已修改
2.  1)升级合约 timelock4 至 v0.1.2 版本的操作变成了新建一个名为“chaincodebuild-ist9e"@dayuy 看下
     2)调用 timelock4 合约显示为未升级状态 @dayuy  看下

**Comment by bjwswang** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/30621793/230819192-e0890de0-8a8e-47e0-ab50-21ddba45de77.png">
 
这个位置刚刚展示的是`chaincodebuild.metadata.name`

**Comment by Lanture1064** [comment]
“调用未升级”指的是【升级合约，出现上述新建合约情况，将新合约按照原方式部署合约至通道上】之后，后端调用 timelock4 合约程序的结果表明 timelock4 仍然是没有升级的版本(v0.1.1)。（可能跟前端关系不大？）
（前端页面显示的合约的版本列表里，timelock4 确实没有 v0.1.2）

**Comment by dayuy** [comment]
升级合约，目前的逻辑是1. 新建一个spec.id相同的chaincodebuild。
@Lanture1064 按照你期望的结果，应该是 「部署合约」

**Comment by bjwswang** [comment]
> “调用未升级”指的是【升级合约，出现上述新建合约情况，将新合约按照原方式部署合约至通道上】之后，后端调用 timelock4 合约程序的结果表明 timelock4 仍然是没有升级的版本(v0.1.1)。（可能跟前端关系不大？） （前端页面显示的合约的版本列表里，timelock4 确实没有 v0.1.2）

这里的升级合约与合约部署没有关系

**Comment by bjwswang** [comment]
> 升级合约，目前的逻辑是1. 新建一个spec.id相同的chaincodebuild。 @Lanture1064 按照你期望的结果，应该是 「部署合约」

这个逻辑没问题，我们是通过相同的spec.id来判断为同一个合约的不同版本。那不应该在list里出现直接展示出类似 `chaincode-xxsd` 的合约。 
上午使用的时候发现，合约升级的时候合约名称变成了`chaincode-xsfs`，估计是这个导致spec.id直接设置成了 `chaincode-xsfs`
