### ISSUE TITLE
合约信息中的合约名称展示错误

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#156]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/30621793/230839956-27cfd531-71e9-497e-bb7e-eb298f3c5840.png">

**Comment by bjwswang** [comment]
@dayuy  使用这个格式展示名称

`chaincode.spec.externalbuilder(chaincode.metadata.name)`

如  basic(chaincode-xerbss)

**Comment by dayuy** [comment]
@Jandiasnow  用 displayName(name)
如 `basic2(chaincodebuild-xkdkw)`
