### ISSUE TITLE
通道数量展示不正常

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#157]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/30621793/230847308-5e5a91a0-4def-4b49-b686-6ebfbf958836.png">

此处应该是 `7/7`

**Comment by dayuy** [comment]
channel（bjwswang-contract-test）spec.members 缺少initiator字段 @bjwswang 
![image](https://user-images.githubusercontent.com/17400942/230857996-8d77d439-030a-4306-ad3d-3fd87c9ea08f.png)

**Comment by bjwswang** [comment]
通道 bjwswang-contract-test为本地手动创建，所以没有initiator
