### ISSUE TITLE
区块链浏览器数据请求的参数不正确

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#171]
区块链浏览器部分：

1. 通道下拉选择框

{network.metadata.name}_{channel.spec.id}

2. 请求通道的区块/交易等数据

{network.metadata.name}_{channel.spec.id}

**Comment by dayuy** [comment]
network 暂时没有 spec.displayName @bjwswang

**Comment by bjwswang** [comment]
> network 暂时没有 spec.displayName @bjwswang

好的，那前段对齐下接口请求数据的参数就ok了
