### ISSUE TITLE
.bcignore没有起作用

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#172]

**Comment by Jandiasnow** [comment]
需要适配 mac 等不同系统

**Comment by bjwswang** [comment]
> 需要适配 mac 等不同系统

收到，目前是支持在哪个系统可用？

**Comment by Jandiasnow** [comment]
目前只支持 windows，添加适配如下：
1、windows操作系统下的换行符是/r/n(回车换行CRLF)；
2、linux操作系统下的换行符是/n(换行LF)；
3、mac操作系统下的换行符是/r(回车CR)；
