### ISSUE TITLE
新增用户的时候参数异常，可能传入了空值

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#20]
![image](https://user-images.githubusercontent.com/30621793/218704379-c652394f-2653-48b4-a7eb-3048311e5e95.png)

点击添加用户，bc-apis可能封装了空的user，导致operator reconcile异常
![image](https://user-images.githubusercontent.com/30621793/218704587-71f37cbf-c0ec-4912-ba2e-8db6fd12a1e1.png)

**Comment by bjwswang** [comment]
@dayuy 需要查验一下

**Comment by dayuy** [comment]
organization的spec.caSpec.images拉取失败，通过环境变量设置image

**Comment by dayuy** [comment]
镜像已经设置了，但还是有这个问题

**Comment by bjwswang** [comment]
@dayuy 
当前组织的admin用户不应作为`clients`一起来更新Organization
