### ISSUE TITLE
网络管理-概览

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#37]

**Comment by marsdawe** [comment]
<img width="701" alt="image" src="https://user-images.githubusercontent.com/44803190/220830185-ccbe2988-ff4d-4ebc-a4a7-d55b5fc841a4.png">
**网络概览**

##快速上链
新建通道--编写并部署合约--业务对接--查看浏览器

##关键指标
我的通道：网络内的我创建的通道、我加入的通道  。
智能合约：我发起的合约、他人发起的合约  。
网络节点：我创建的节点、他人创建的节点。
网络组织：我创建的组织、他人创建的组织。  

##网络基础信息
网络名称：网络创建时的名称，不可重复。
所属联盟：网络所属联盟。  
创建时间：网络创建时间。  
更新时间：网络最近一次更新通道、合约时间。  
状态：网络运营状态，和网络列表页保持一致。
介绍：网络介绍，创建时填写。  

##网络配置信息  
版本：创建网络时选择的版本。  
节点配置：默认配置。  
节点存储：默认配置。  
状态数据库类型：默认配置。
