### ISSUE TITLE
通道管理

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#38]
- [x] 通道列表查看
- [x] 新建通道页面
- [x] 节点加入通道页面

**Comment by marsdawe** [comment]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/44803190/220532342-80b983bd-972c-4de1-a854-a4eed11e0699.png">

**Comment by marsdawe** [comment]
通道管理
       显示网络内的通道列表。
  1、新建通道    
<img width="629" alt="image" src="https://user-images.githubusercontent.com/44803190/220808101-cbe1f99b-429a-4eb6-bc76-9c8279c2526c.png">
<img width="681" alt="image" src="https://user-images.githubusercontent.com/44803190/220814005-af212baa-9253-4bba-9379-3095baa94a1a.png">

a、创建者选择发起组织不选择配置成员创建通道，选择发起者（自己组织）的节点加入通道，创建成功后才能邀请自己创建的其他组织，以及加入网络内其他人创建的组织加入通道。
b、创建者选择自己组织的同时可以选择配置成员，这个时候需要发起邀请，需要配置的成员同意才可创建通道。
      1.1、 通道名称：必填，文本，支持小写字母和数字，并且字母开头，通道名字不能和通道内名字重复，如果重复显示“通道名字重复”
      1.2、 配置组织成员：非必选，支持多选，添加多个组织，发出邀请后，对方同意后，需要遵循投票策略。
      1.3   描述：非必填，可以为空，最多200字。
      1.4、提交，通道名称和选择了组织后，按钮会高亮，才可以进行提交

   2、通道列表
<img width="700" alt="image" src="https://user-images.githubusercontent.com/44803190/220808024-70184af8-ccf4-4f57-9fed-e7b7050739c2.png">

      2.1 列表字段  通道名、组织数量（通道内组织的数量）、我的节点数量、合约数量
 、加入时间、状态
           组织数量：点击组织数量，toast显示加入通道内组织的名字。
           我的节点：点击节点数量，toast显示我的加入通道内节点的名字。
           状态：通道的状态（和后端保持一致）
                       创建中、创建失败、运行中
                       增加组织中、增加组织失败
                       节点加入中、节点加入失败
        2.2、操作：
             邀请组织：邀请联盟下组织加入通道。用户点击邀请组织时候，需要判断是否加入了节点，如果没有加入节点，就不能邀请自己或者其他的组织，toast提示“还没加入节点“，如果已经加入节点，点击邀请组织，出现邀请组织的弹窗；
            邀请弹窗可以输入组织名字进行检索，支持多选，邀请多个组织进入通道，如果没有组织数据或者有组织数据没有勾选，【加入】按钮置灰色，不可点击，选中组织后，【加入】按钮置高亮可以点击
          当通道中有其他用户组织时，需要其他用户投票同意，才能加入成功

            加入节点：选择已经加入通道的组织里面节点进入通道。 点击“”加入节点“，出现通道加入节点的弹窗，如果加入通道的组织的节点已经全部加入，会显示”还没有任何待添加的节点“，如果组织下还有节点没有加入，会显示组织，点击组织，展开节点显示节点名字，勾选组织，就会将组织下面的节点全选，也可以只勾选节点，如果将组织下面的节点全部选择，对应的组织也会被勾选；勾选后，加入按钮才能高亮和点击。

  3、通道详情页
<img width="690" alt="image" src="https://user-images.githubusercontent.com/44803190/220811836-47f7863c-c7b7-40b6-8e1d-29f0aae60d7a.png">

     3.1、基本信息
           通道名字、通道描述、创建时间
     3.2、合约信息
           列表展示部署在通道的合约名字和版本
      3.3、组织
         列表展示加入通道的成员组织
       3.4、节点
        列表展示通道中的节点。
       3.5、背书策略
      列表展示通道中的背书策略

**Comment by marsdawe** [comment]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/44803190/220567456-12db7afb-3d31-4976-8a31-aaf5bf67727d.png">
