### ISSUE TITLE
合约管理

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#40]
- [x] 合约列表
- [x] 新建合约
- [x] 合约部署
- [x] 合约升级

**Comment by marsdawe** [comment]
**合约管理**


合约列表页

<img width="823" alt="image" src="https://user-images.githubusercontent.com/44803190/220806670-e06dcca1-49ac-42d4-af74-04f281aaf800.png">

        新建合约之后，可以在合约列表查看，选择合约安装部署到通道。将未安装部署的合约进行升级，需要再次部署。
   1.1、列表字段
合约列表
“合约名称”：合约唯一标识。
“版本”：该合约拥有的版本，展开可以看到具体每个版本情况，每升级一次，有一个版本。
“创建时间”：合约安装或最近一次合约升级的时间。
“合约来源”：合约来源，目前有“自己发起”。以后有“合约商店”。
“部署节点数”：合约部署了多少个节点。
“部署通道数”：合约部署了多少个通道。

   1.2、操作
部署：将上传的合约安装部署到通道，点击部署，出现安装部署合约的弹窗，
<img width="616" alt="image" src="https://user-images.githubusercontent.com/44803190/220806772-e336d898-96d3-4103-91a0-0b59a9571291.png">


                   合约名字不能编写；
                   合约版本号：下拉选择，单选，必选；
                   选择安装节点，当前通道内的自己组织下面的节点，可以多选。
                   部署通道:下拉选择，单选，必选；
                   背书策略：下拉选择，非必选，如果点击没数据，显示“暂无数据”；
                   确定：点击【确定】按钮提交部署信息，发送提议，遵循联盟投票策略进行投票。

         升级：将已存在的合约升级到本地点击升级，出现升级合约的弹窗，
<img width="640" alt="image" src="https://user-images.githubusercontent.com/44803190/220806871-43e1c8b3-d243-4445-a767-2bf769ff9ebd.png">

                   合约名字不能编写；
                   当前合约版本号不能改变
                   输入升级后的版本号。
                   上传合约压缩包
                   确定：点击【确定】按钮提交升级信息
         删除：没有安装部署的合约可以删除，点击【删除】，出现确认弹窗，点击确定后，执行删除操作。

合约详情页面
<img width="709" alt="image" src="https://user-images.githubusercontent.com/44803190/220806941-6d05cd76-13bf-4b9a-92b4-f2c3196f851d.png">

       基本信息：名称、版本号、创建时间、来源、发起组织、合约正文下载
                        下载：以压缩包形式下载代码文件，合约标识+版本号
         组织：合约安装部署的组织
         节点：合约安装部署的节点
         通道：合约安装的通道
