### ISSUE TITLE
出码后 table 表头背景色问题

### ISSUE THREAD

**Issue by Carrotzpc** [bestchains/bc-console#53]
预览时：

![Image](https://user-images.githubusercontent.com/10265417/220262539-e7b5f25e-8d3b-490c-9e14-d4a06381d486.png)

出码后：

![Image](https://user-images.githubusercontent.com/10265417/220262475-20b4a15c-3be4-44be-94e9-54f2a3cc4de6.png)

期望出码后能跟预览时保持一致

**Comment by Jandiasnow** [comment]
加入 dock-app 后出现的问题，需要帮忙看下 @zggmd
