### ISSUE TITLE
组织管理-组织新增用户不正确提示

### ISSUE THREAD

**Issue by marsdawe** [bestchains/bc-console#66]
1. 组织新增用户时，如果输入的用户不存在，仍提示邀请成功，应提示用户不存在！
2. 情况1出现之后，组织状态变为“异常”

**Comment by marsdawe** [comment]
![image](https://user-images.githubusercontent.com/44803190/223309566-92c49168-4a2b-4da0-b803-179f47e6ce44.png)

**Comment by Jandiasnow** [comment]
需要提供校验接口，或提供报错信息 @dayuy

**Comment by bjwswang** [comment]
@marsdawe 后端也增加校验

**Comment by dayuy** [comment]
建议：1. 这里是不是可以搞成多选框，选择已有成员（可搜索）@marsdawe
2. bff 会加校验

**Comment by bjwswang** [comment]
> @marsdawe 后端也增加校验

后端已经添加对用户是否存在的校验

**Comment by dayuy** [comment]
bff 已加校验

**Comment by marsdawe** [comment]
![image](https://user-images.githubusercontent.com/44803190/230558019-a3b06610-1f68-4f30-a89f-cd85da297666.png)
应提示“用户不存在”
