### ISSUE TITLE
网络管理-通道管理-新建通道不显示

### ISSUE THREAD

**Issue by marsdawe** [bestchains/bc-console#70]
1、新建通道完成后，通道列表不显示。创建成功应在列表显示通道数据。
2、再次新建同名通道时，报错，应在输入名字时正则校验和名字去重校验。

![image](https://user-images.githubusercontent.com/44803190/223335422-1917b1e0-b1d0-415e-9f28-954a2b077452.png)

**Comment by Jandiasnow** [comment]
需要提供校验接口 @dayuy

**Comment by dayuy** [comment]
通道详情：如果能够获取到详情，则存在
query getChannel($name: String!)

**Comment by dayuy** [comment]
> a

# 通道详情：如果能够获取到详情，则存在
query getChannel($name: String!)
