### ISSUE TITLE
网络管理-通道管理，通道列表不显示组织加入时间，状态显示未知

### ISSUE THREAD

**Issue by marsdawe** [bestchains/bc-console#72]
![image](https://user-images.githubusercontent.com/44803190/223627824-addbd2ef-0716-49cf-940b-317611d6d7ed.png)

**Comment by Jandiasnow** [comment]
@dayuy 需要提供相关字段

**Comment by dayuy** [comment]
加入时间：members[0].joinedAt
状态： Created、Error、ChannelCreated、ChannelArchived
![image](https://user-images.githubusercontent.com/17400942/226265991-743a109e-ee2c-4485-afc4-eb8571979fb5.png)
