### ISSUE TITLE
网络管理-删除网络错误

### ISSUE THREAD

**Issue by marsdawe** [bestchains/bc-console#74]
删除网络逻辑有误
先停止网络，在删除网络，删除网络权限只有网络创建者拥有，对应状态和操作显示逻辑如下：

网络运行中：显示“停止”，不显示“删除网络”操作。
网络停止：显示“删除网络”，此时非网络管理者，置灰“删除网络”不可操作，网络管理者可以点击“删除网络”执行操作。
参照设计图

![image](https://user-images.githubusercontent.com/44803190/223664029-aaff5ec9-3062-412f-8fe0-66773aa3dee5.png)

**Comment by Jandiasnow** [comment]
1. 需要 bff-server 确认对应的状态值 @dayuy 
网络运行中：显示“停止”，不显示“删除网络”操作。
网络停止：显示“删除网络”
2.非网络管理者，置灰“删除网络”不可操作 已修改

**Comment by dayuy** [comment]
Network.status:
状态（网络运行中：Deployed，网络停止：NetworkDissolved） @Jandiasnow
