### ISSUE TITLE
联盟管理-联盟创建人显示错误，

### ISSUE THREAD

**Issue by marsdawe** [bestchains/bc-console#76]
1、联盟列表和联盟详情中，创建人应该是组织，不是用户。
2、联盟详情下成员，显示组织，不是用户。
3、联盟详情下网络创建者，显示组织，不是用户。
![image](https://user-images.githubusercontent.com/44803190/223941927-c766041b-5ff1-4375-a65b-e641e80b0396.png)

**Comment by Jandiasnow** [comment]
1. 联盟列表没有问题，不做修改 ，联盟详情已修改
2. 详情下就是显示的组织不是成员，不做修改
3. 已修改
