### ISSUE TITLE
网络管理-新建网络-必填信息及名称规范页面显示与实际不符

### ISSUE THREAD

**Issue by Lanture1064** [bestchains/bc-console#81]
![66DFBBFD-5A8D-4bc5-A7A9-8939BE57543F](https://user-images.githubusercontent.com/34346740/224643600-70b719c6-cc4f-4920-acd9-834628e5d94e.png)
![822B4675-0B14-4618-BB4C-359E67426B3B](https://user-images.githubusercontent.com/34346740/224643612-9b73a059-48b6-4fb1-b8e9-a5e1ff69616b.png)

原文：
`{
  "message": "HTTP request failed",
  "locations": [
    {
      "line": 2,
      "column": 3
    }
  ],
  "path": [
    "networkCreate"
  ],
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR",
    "exception": {
      "response": {
        "statusCode": 422,
        "body": {
          "kind": "Status",
          "apiVersion": "v1",
          "metadata": {},
          "status": "Failure",
          "message": "Network.ibp.com \"river_net\" is invalid: metadata.name: Invalid value: \"river_net\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')",
          "reason": "Invalid",
          "details": {
            "name": "river_net",
            "group": "ibp.com",
            "kind": "Network",
            "causes": [
              {
                "reason": "FieldValueInvalid",
                "message": "Invalid value: \"river_net\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')",
                "field": "metadata.name"
              }
            ]
          },
          "code": 422
        },
        "headers": {
          "cache-control": "no-cache, private",
          "content-length": "906",
          "content-type": "application/json",
          "date": "Mon, 13 Mar 2023 08:10:32 GMT",
          "x-kubernetes-pf-flowschema-uid": "17c72ac8-56d3-43c2-b506-88369b3dfd6c",
          "x-kubernetes-pf-prioritylevel-uid": "0fbaace5-3e9b-4c80-933e-7035f7939373",
          "connection": "close"
        },
        "request": {
          "uri": {
            "protocol": "https:",
            "slashes": true,
            "auth": null,
            "host": "172.22.96.146:9443",
            "port": "9443",
            "hostname": "172.22.96.146",
            "hash": null,
            "search": null,
            "query": null,
            "pathname": "/apis/ibp.com/v1beta1/networks",
            "path": "/apis/ibp.com/v1beta1/networks",
            "href": "https://172.22.96.146:9443/apis/ibp.com/v1beta1/networks"
          },
          "method": "POST",
          "headers": {
            "Accept": "application/json",
            "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjYwOTJkMWZiY2UwN2U1M2RiYzdhNWNmOGRmOTIzZWI2MTc5MjE2NDYifQ.eyJpc3MiOiJodHRwczovL3BvcnRhbC4xNzIuMjIuOTYuMjA5Lm5pcC5pby9vaWRjIiwic3ViIjoiQ2dWa1lYbDFlUklHYXpoelkzSmsiLCJhdWQiOiJiZmYtY2xpZW50IiwiZXhwIjoxNjc4Nzc3NzU0LCJpYXQiOjE2Nzg2OTEzNTQsImF0X2hhc2giOiJVUVFid0Y2VnBuSEZMSVk1bG10TzJBIiwiY19oYXNoIjoiUU9JMXd5ejlwbTdkVWZCVVU3S3VSUSIsImVtYWlsIjoiYWRtaW5AdGVueGNsb3VkLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJncm91cHMiOlsiaWFtLnRlbnhjbG91ZC5jb20iLCJvYnNldmFiaWxpdHkiLCJyZXNvdXJjZS1yZWFkZXIiLCJiZXN0Y2hhaW5zIl0sIm5hbWUiOiJkYXl1eSIsInByZWZlcnJlZF91c2VybmFtZSI6ImRheXV5IiwicGhvbmUiOiIiLCJ1c2VyaWQiOiJkYXl1eSJ9.kteyQoEyK6QrealQIwWGjjkpnEsboFjasvowLP3gIQTijRoJgl6BtLwtv4AjfZ4jYkbR8UmccUxFsBHy6B6Yh-voEerWlDIe7mrtHxeWxHzUnGOy2arW13WpakCm6Rv7Wrc2sgwAx5fc9_ZSW6A__8ph2xJkyaL2ryHjUeYEcYHNGJtKpf8iRAqnb1qJGcAIiCQmKCI0I8nMCWDLVNX-uXWnaCW-d5U80N4q_lDS4QtHh3QnBKXySdF62LSucBuo1dFWxPA5FB_n4FawUO9K8sIoLT94f_4umldLb_bkDhahgqOWRMVG1WZPv67ZQhYrIxJsEYcKGwEv-glJ8Oa6zw",
            "X-Forwarded-For": "127.0.0.1",
            "content-type": "application/json",
            "content-length": 1798
          }
        }
      },
      "body": {
        "kind": "Status",
        "apiVersion": "v1",
        "metadata": {},
        "status": "Failure",
        "message": "Network.ibp.com \"river_net\" is invalid: metadata.name: Invalid value: \"river_net\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')",
        "reason": "Invalid",
        "details": {
          "name": "river_net",
          "group": "ibp.com",
          "kind": "Network",
          "causes": [
            {
              "reason": "FieldValueInvalid",
              "message": "Invalid value: \"river_net\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')",
              "field": "metadata.name"
            }
          ]
        },
        "code": 422
      },
      "statusCode": 422,
      "name": "HttpError"
    }
  }
}`

此外，下面共识算法的部分应该也是必填项，不填会报错，需要加星号

**Comment by bjwswang** [comment]
same issue https://github.com/bestchains/bc-console/issues/83

**Comment by Jandiasnow** [comment]
之前前端的校验规则：网络名称由 3 ~ 20 个小写字母, 数字, 下划线组成
需要提供下正确的规则，前后端统一 @marsdawe

**Comment by dayuy** [comment]
网络名称，规则：小写字母、数字、“-”，开头和结尾只能是字母或数字`（[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*）`

**Comment by dayuy** [comment]
![image](https://user-images.githubusercontent.com/17400942/225843972-64c43bf8-d6b3-424f-a23c-5c7955c78a8a.png)
这种Input里的name需要校验的，都会在图片里标注
