### ISSUE TITLE
网络管理-新建通道操作没有在提议管理中显示，状态为未知

### ISSUE THREAD

**Issue by Lanture1064** [bestchains/bc-console#85]
操作：基于已创建的包含2个组织，4个节点的网络，建立组织间新通道
结果：页面提示【在提议管理中查看进度】，但提议管理中未显示相应提案，创建后的通道状态显示为未知，不能确认之后的合约部署操作能否正常进行
![Dingtalk_20230315150253](https://user-images.githubusercontent.com/34346740/225231857-7ca6366c-1985-4852-8b76-856b16874eaa.jpg)
![Dingtalk_20230315150156](https://user-images.githubusercontent.com/34346740/225231869-ff0225ac-aee3-440a-ac79-e9a29b430ac3.jpg)
![Dingtalk_20230315150233](https://user-images.githubusercontent.com/34346740/225231875-c6047f39-5145-4016-8d93-fe8cad682486.jpg)

**Comment by dayuy** [comment]
@Lanture1064  新建通道不需要投票，这里看看设计稿是不是需要改下？

**Comment by Jandiasnow** [comment]
经产品确认：如果没有配置成员则不需要发起提议，如果配置成员了，就需要发起提议;
前端已修改
