### ISSUE TITLE
背书策略创建格式问题

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#95]
背书策略创建失败

## 期望
1. 选择通道后，自动展开一行 `AND` 条件

## 实际

![image](https://user-images.githubusercontent.com/30621793/225272931-9bdf1a44-56b3-4a55-9ed0-2f3d2e8f8796.png)

**Comment by bjwswang** [comment]
- 单行不包括OR
- 多行之间OR

**Comment by Jandiasnow** [comment]
修改如下：
1. 切换通道，条件清空，默认添加一条空数据（必填）
2. 条件括号有误
3. 单行不需要添加 OR()
